# Generated by Django 3.2.8 on 2024-05-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='phote',
            new_name='photo',
        ),
    ]
